### ISSUE TITLE
default password isn't always set

### ISSUE THREAD

**Issue by doctorcolossus** [n8henrie/pycookiecheat#14]
So I don't store any passwords in chromium and have never set a master password. I don't use gnome-keyring for anything, but it's installed. pycookiecheat fails because no "my_pass" key gets set in the config dict. The default key only gets set if this try block fails:

    try:
        import gi
        gi.require_version('Secret', '1')
        from gi.repository import Secret
    except ImportError:
        config['my_pass'] = 'peanuts'

In my case, the try block executes fine. However, there just isn't any "Chrome Safe Storage" in the keyring. In fact, there seems to be nothing in it (the outer loop iterates over one item, but there are no items for the inner loop to iterate in my case):

    else:
        flags = Secret.ServiceFlags.LOAD_COLLECTIONS
        service = Secret.Service.get_sync(flags)

        gnome_keyring = service.get_collections()
        unlocked_keyrings = service.unlock_sync(gnome_keyring).unlocked

        for unlocked_keyring in unlocked_keyrings:
            for item in unlocked_keyring.get_items():
                if item.get_label() == "Chrome Safe Storage":
                    item.load_secret_sync()
                    config['my_pass'] = item.get_secret().get_text()
                    break
            else:
                # Inner loop didn't `break`, keep looking
                continue

            # Inner loop did `break`, so `break` outer loop
            break

I tried the following and now everything works great:

    def get_linux_config() -> dict:
        config = dict()  # type: Dict[str, Any]
        config.update({
            'my_pass': 'peanuts',
            'iterations': 1,
            'cookie_file': '~/.config/chromium/Default/Cookies',
            })
        return config

So the problem seems to be that the default password is not set by... default.

Thanks for your script!

**Comment by n8henrie** [comment]
Huh, thanks for the report. I'll take a look.

**Comment by n8henrie** [comment]
@doctorcolossus Can you try the latest dev branch to make sure it's fixed?

**Comment by doctorcolossus** [comment]
Unfortunately the latest dev branch still doesn't work for me:

    $ python
    Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
    [GCC 6.3.1 20170306] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pycookiecheat import chrome_cookies
    >>> url = 'http://www.example.com/'
    >>> cookies = chrome_cookies(url)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/casey/pycookiecheat/pycookiecheat/pycookiecheat.py", line 159, in chrome_cookies
        password=config['my_pass'].encode('utf8'),
    KeyError: 'my_pass'

I tried running this block in the python shell and no errors:

    import gi
    gi.require_version('Secret', '1')
    from gi.repository import Secret

This seems to just test for libsecret, which I do have installed since it's a dependency of gnupg and webkit2gtk, among others.

I inserted a print statement into the else block to check if it runs, and it does. However, no password is getting set. What would the harm be in just setting the default password initially, outside of any conditionals or try/except blocks, then simply overwriting it if a password is then found in the keyring? If nothing is found there, it will simply persist, but this way you can be sure that it will not be empty.

**Comment by n8henrie** [comment]
> What would the harm be in just setting the default password initially, outside of any conditionals or try/except blocks, then simply overwriting it if a password is then found in the keyring?

This is what I intended to do with that latest commit (see the diff). Can you verify that you're using the right code? (I.e. Did you make sure to uninstall before you install, since I didn't yet increment the version number, or better yet use a fresh venv?)

**Comment by doctorcolossus** [comment]
Sorry, my bad. I cloned the latest but just forgot to switch branches.
Now I get a different error though:

    $ python
    Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
    [GCC 6.3.1 20170306] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pycookiecheat import chrome_cookies
    >>> url = 'http://www.example.com/'
    >>> cookies = chrome_cookies(url)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/casey/pycookiecheat/pycookiecheat/pycookiecheat.py", line 162, in chrome_cookies
        dklen=config['length'])
    TypeError: an integer is required (got type str)

**Comment by n8henrie** [comment]
Sorry, was a silly error but only showed up on Linux (didn't pop up on my local machine because I'm on OS X, luckily was caught on Travis as well as by you). Should be fixed now, please try again.

**Comment by n8henrie** [comment]
@doctorcolossus Any updates on the newest version?

**Comment by n8henrie** [comment]
10 days without a response -- going to merge and hope that the issue was resolved.

**Comment by doctorcolossus** [comment]
Hey n8henrie, sorry. I have had limited internet access lately. I just tested and I'm still getting a KeyError. :(

    $ git clone https://github.com/n8henrie/pycookiecheat.git
    Cloning into 'pycookiecheat'...
    cd remote: Counting objects: 560, done.
    remote: Total 560 (delta 0), reused 0 (delta 0), pack-reused 560
    Receiving objects: 100% (560/560), 83.53 KiB | 89.00 KiB/s, done.
    Resolving deltas: 100% (267/267), done.
    $ git checkout dev
    Switched to branch 'dev'
    $ python
    Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
    [GCC 6.3.1 20170306] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pycookiecheat import chrome_cookies
    >>> import requests
    >>> url = 'http://example.com/fake.html'
    >>> cookies = chrome_cookies(url)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/casey/pycookiecheat/pycookiecheat/pycookiecheat.py", line 159, in chrome_cookies
        password=config['my_pass'].encode('utf8'),
    KeyError: 'my_pass'
    >>>

**Comment by n8henrie** [comment]
Awesome, thanks for the feedback and for the bug report.
